import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import the Geist font styles
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Check for the user's system dark mode preference
  const prefersDarkMode = typeof window !== "undefined" && window.matchMedia('(prefers-color-scheme: dark)').matches;

  // Add dark class to the body if the user prefers dark mode
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${prefersDarkMode ? 'dark' : ''}`}
      >
        {children}
      </body>
    </html>
  );
}
